### ISSUE TITLE
DeepPhe-CR- fails to star

### ISSUE THREAD

**Issue by harryhoch** [DeepPhe/DeepPhe-CR-Release#1]
Tried to follow instructions for starting DeepPhe-CR. Difficulties ensue.

Environment:  Mac OS 12.4, Docker desktop 4.10.1, Engine 20.10.17. 

Symptoms: 

run build,

docker-compose up -d, and 
docker-compose logs -f --tail="all" 

get the following logs. Port 80 doesn't seem to respond...

    | 2022-07-25 13:18:01.261  INFO 8 --- [           main] o.s.b.web.embedded.jetty.JettyWebServer  : Jetty started on port(s) 8080 (http/1.1) with context path '/'
dphe-stream        | 2022-07-25 13:18:01.277  INFO 8 --- [           main] o.h.d.stream.rest.StreamRestApplication  : Started StreamRestApplication in 17.982 seconds (JVM running for 18.462)
dphe-stream-nginx exited with code 1
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx exited with code 1
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx  | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx  | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx exited with code 1

**Comment by seanfinan** [comment]
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
Does the user that is trying to run have rw permission?
________________________________
From: Harry Hochheiser ***@***.***>
Sent: Monday, July 25, 2022 9:30 AM
To: DeepPhe/DeepPhe-CR-Release ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DeepPhe/DeepPhe-CR-Release] DeepPhe-CR- fails to star (Issue #1) [EXTERNAL]

* External Email - Caution *


Tried to follow instructions for starting DeepPhe-CR. Difficulties ensue.

Environment: Mac OS 12.4, Docker desktop 4.10.1, Engine 20.10.17.

Symptoms:

run build,

docker-compose up -d, and
docker-compose logs -f --tail="all"

get the following logs. Port 80 doesn't seem to respond...

| 2022-07-25 13:18:01.261  INFO 8 --- [           main] o.s.b.web.embedded.jetty.JettyWebServer  : Jetty started on port(s) 8080 (http/1.1) with context path '/'


dphe-stream | 2022-07-25 13:18:01.277 INFO 8 --- [ main] o.h.d.stream.rest.StreamRestApplication : Started StreamRestApplication in 17.982 seconds (JVM running for 18.462)
dphe-stream-nginx exited with code 1
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx exited with code 1
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx | Starting dphe-stream-nginx container with the same host user UID: 1000 and GID: 1000
dphe-stream-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dphe-stream-nginx exited with code 1

**Comment by harryhoch** [comment]
how do I tell? should I run docker as sudo as discussed in the Linux docs?

**Comment by seanfinan** [comment]
I just checked the wiki and couldn't find anything about running with sudo.  Is it in one of the offline docs?

**Comment by harryhoch** [comment]
https://github.com/DeepPhe/DeepPhe-CR-Release#docker-post-installation-configurations---optional discusses the use of sudo

**Comment by harryhoch** [comment]
I did the following before docker-compose up

“export HOST_UID=1000; export HOST_GID=1000”

Got the same result.

**Comment by yuanzhou** [comment]
@harryhoch I just did a fresh build with the released code https://github.com/DeepPhe/DeepPhe-CR-Release/releases/download/v0.2.0-cr/v0.2.0-cr.zip on my Fedora35 installed on the VirtualBox. And the build went well and the two containers spin up with no errors. I can't reproduce this permission error with the nginx container.

My host use account has the uid and gid as 1000, which is the default docker-compose settings https://github.com/DeepPhe/DeepPhe-CR-Release/blob/main/docker-compose.yml#L34-L36 for running the process within the container.

```
[zhy19@fedora v0.2.0-cr]$ id
uid=1000(zhy19) gid=1000(zhy19) groups=1000(zhy19),10(wheel),977(docker)
[zhy19@fedora v0.2.0-cr]$ docker-compose up
```

To debug the issue you had, can you shell into the container by `docker exec -it dphe-stream-nginx bash` then check the permission? Below is what I got. The user `deepphe` is actually the mapped user from the host user with uid and gid 1000.

```
[root@dphe-stream-nginx app]# cd /etc/nginx/conf.d/
[root@dphe-stream-nginx conf.d]# ls -al
total 4
drwxr-xr-x 1 root    root      32 Jul 25 15:23 .
drwxr-xr-x 1 root    root     140 Jul 25 15:21 ..
-rw-rw-r-- 1 deepphe deepphe 1400 Nov  5  2020 dphe-stream.conf
[root@dphe-stream-nginx conf.d]# cd ../
[root@dphe-stream-nginx nginx]# ls -al
total 28
drwxr-xr-x 1 root root  140 Jul 25 15:21 .
drwxr-xr-x 1 root root 2026 Jul 25 15:23 ..
drwxr-xr-x 1 root root   32 Jul 25 15:23 conf.d
-rw-r--r-- 1 root root 1007 Jul 19 15:21 fastcgi_params
-rw-r--r-- 1 root root 5349 Jul 19 15:21 mime.types
lrwxrwxrwx 1 root root   29 Jul 25 15:21 modules -> ../../usr/lib64/nginx/modules
-rw-rw-r-- 1 root root  800 Nov  5  2020 nginx.conf
-rw-r--r-- 1 root root  636 Jul 19 15:21 scgi_params
-rw-r--r-- 1 root root  664 Jul 19 15:21 uwsgi_params
[root@dphe-stream-nginx nginx]# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by harryhoch** [comment]
ok, Zhou. Tried it on a different Mac. Got it to work and then ran into a different problem.

basically, it ran once and then it wouldn't process any more documents, giving a "bad gateway" error. 
[deephe-cr-log-20220725.txt](https://github.com/DeepPhe/DeepPhe-CR-Release/files/9184558/deephe-cr-log-20220725.txt)

Log attached. Any idea what might be up?
[](url)

**Comment by yuanzhou** [comment]
@harryhoch looking at the logging file, I can't tell anything wrong with the REST API. The 502 issue can be an nginx error. The first couple of lines do imply the nginx container was up running. Can you try with restarting the containers?

**Comment by harryhoch** [comment]
Hmm. seems to be working better now. Not sure why. will monitor and let you know.
